// Pending Appointment Actions
export const UPDATE_PENDING_APPOINTMENT = "UPDATE_PENDING_APPOINTMENT";
export const SET_APPOINTMENT_DATE = "SET_APPOINTMENT_DATE";
export const CLEAR_PENDING_APPOINTMENT = "CLEAR_PENDING_APPOINTMENT";

// Scheduled Appointment Actions
export const SAVE_APPOINTMENT = "SAVE_APPOINTMENT";
